// LocalizableErrorMacro.swift
//
// Copyright 2025 FOS Computer Services, LLC
//
// Licensed under the Apache License, Version 2.0 (the  License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if os(macOS) || os(Linux) || os(Windows)
public import SwiftSyntax
public import SwiftSyntaxMacros
import SwiftSyntaxBuilder

public enum LocalizableErrorMacroError: Error, CustomDebugStringConvertible {
    case onlyStructs

    public var debugDescription: String {
        switch self {
        case .onlyStructs:
            "LocalizableErrorMacroError: @LocalizableError can only be applied to structs"
        }
    }
}

// Example:
//
// @LocalizableError
// struct MyError/* : LocalizableError <- No need to add, will be added automatically */ {
//   @LocalizedString public var errorMessage
//
//   public var localizedMessage: any Localizable { errorMessage }
//
//   // This function is generated by the macro
//   public func propertyNames() -> [LocalizableId: String] { [
//      errorMessage.localizationId: "errorMessage"
//   ] }
// }
//

/// Mirrors FOSMVVM.LocalizableErrorOptions for attribute parsing — keep the two in sync
private enum LocalizableErrorOptions: String {
    case clientHosted
}

public struct LocalizableErrorMacro: ExtensionMacro, MemberMacro {
    /// Keep in sync with ViewModelMacro.knownLocalizedPropertyNames and
    /// FieldValidationModelMacro.knownLocalizedPropertyNames
    private static let knownLocalizedPropertyNames = [
        // _LocalizedProperty
        "LocalizedString",
        "LocalizedInt",
        "LocalizedDouble",
        "LocalizedDate",
        "LocalizedCompoundString",
        "LocalizedSubs",

        // _LocalizedArrayProperty
        "LocalizedStrings"
    ]

    // MARK: Extension Macro Protocol

    public static func expansion(
        of node: AttributeSyntax,
        attachedTo declaration: some DeclGroupSyntax,
        providingExtensionsOf type: some TypeSyntaxProtocol,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [ExtensionDeclSyntax] {
        guard node.attributeName.description.trimmingCharacters(in: .whitespaces) == "LocalizableError" else {
            return []
        }

        // Ensure the declaration is a struct
        guard let structDecl = declaration.as(StructDeclSyntax.self) else {
            throw LocalizableErrorMacroError.onlyStructs
        }

        var result = [ExtensionDeclSyntax]()

        // .clientHosted lists the marker BESIDE the base conformance in one clause — a
        // macro-emitted extension registers only the conformances it spells out; the
        // marker's refinement of LocalizableError is not implied through it.
        let errorConformances = node.errorOptions.contains(.clientHosted)
            ? ["LocalizableError", "ClientHostedLocalizableError"]
            : ["LocalizableError"]

        // Skip extension generation if the conformance is explicitly declared
        // Note: Indirect conformances (via other protocols) are not detected due to SwiftSyntax limitations
        if !structDecl.conformsTo("LocalizableError"), !structDecl.conformsTo("ClientHostedLocalizableError") {
            let extensionDecl = ExtensionDeclSyntax(
                extendedType: type,
                inheritanceClause: InheritanceClauseSyntax {
                    for conformance in errorConformances {
                        InheritedTypeSyntax(type: TypeSyntax(stringLiteral: conformance))
                    }
                },
                memberBlock: MemberBlockSyntax(members: [])
            )

            result.append(extensionDecl)
        }

        // Skip extension generation if RetrievablePropertyNames is explicitly declared
        // Note: Indirect conformances (via other protocols) are not detected due to SwiftSyntax limitations
        if !structDecl.conformsTo("RetrievablePropertyNames") {
            let extensionDecl = ExtensionDeclSyntax(
                extendedType: type,
                inheritanceClause: InheritanceClauseSyntax {
                    InheritedTypeSyntax(type: TypeSyntax(stringLiteral: "RetrievablePropertyNames"))
                },
                memberBlock: MemberBlockSyntax(members: [])
            )

            result.append(extensionDecl)
        }

        return result
    }

    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard node.attributeName.description.trimmingCharacters(in: .whitespaces) == "LocalizableError" else {
            return []
        }

        // Ensure the declaration is a struct
        guard let structDecl = declaration.as(StructDeclSyntax.self) else {
            throw LocalizableErrorMacroError.onlyStructs
        }

        // Collect properties with _LocalizedProperty wrapper
        let properties = structDecl.memberBlock.members.compactMap { member -> (name: String, id: String)? in
            guard let varDecl = member.decl.as(VariableDeclSyntax.self),
                  let binding = varDecl.bindings.first,
                  let identifier = binding.pattern.as(IdentifierPatternSyntax.self)?.identifier.text
            else {
                return nil
            }

            let hasLocalizedWrapper = varDecl.attributes.contains { attribute in
                guard let attr = attribute.as(AttributeSyntax.self) else { return false }
                let attrName = attr.attributeName.description.trimmingCharacters(in: .whitespaces)
                return Self.knownLocalizedPropertyNames.contains(attrName)
            }

            guard hasLocalizedWrapper else { return nil }

            return (name: identifier, id: "\(identifier).localizationId")
        }

        var newDecls: [DeclSyntax] = []

        // Generate the propertyNames function
        var pairs = properties.map { "_\($0.id): \"\($0.name)\"" }.joined(separator: ", ")
        if pairs.isEmpty {
            pairs = ":"
        }
        let propertyNamesDecl = try FunctionDeclSyntax(
            """
            public func propertyNames() -> [LocalizableId: String] {
                [\(raw: pairs)]
            }
            """
        )
        newDecls.append(DeclSyntax(propertyNamesDecl))

        return newDecls
    }
}

private extension AttributeSyntax {
    var errorOptions: Set<LocalizableErrorOptions> {
        if let argumentList = arguments?.as(LabeledExprListSyntax.self),
           let optionsElement = argumentList.first(where: { $0.label?.text == "options" }),
           let arrayExpr = optionsElement.expression.as(ArrayExprSyntax.self) {
            Set(arrayExpr.elements.map(\.expression)
                .compactMap { $0.as(MemberAccessExprSyntax.self)?.declName }
                .map(\.baseName.text)
                .compactMap { LocalizableErrorOptions(rawValue: $0) })
        } else {
            []
        }
    }
}

private extension StructDeclSyntax {
    func conformsTo(_ protocolName: String) -> Bool {
        inheritanceClause?.inheritedTypes.contains { inheritedType in
            if let identifierType = inheritedType.type.as(IdentifierTypeSyntax.self) {
                identifierType.name.text == protocolName
            } else {
                false
            }
        } ?? false
    }
}
#endif
