// ViewModelMacro.swift
//
// Copyright 2025 FOS Computer Services, LLC
//
// Licensed under the Apache License, Version 2.0 (the  License);
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#if os(macOS) || os(Linux) || os(Windows)
public import SwiftSyntax
public import SwiftSyntaxMacros
import SwiftDiagnostics
import SwiftSyntaxBuilder

public enum ViewModelMacroError: Error, CustomDebugStringConvertible {
    case onlyStructs

    public var debugDescription: String {
        switch self {
        case .onlyStructs:
            "ViewModelMacroError: @ViewModel can only be applied to structs"
        }
    }
}

// The customer-facing message for the `.live` + `.clientHostedFactory` conflict (spec §3.4 v1
// constraint): a client-hosted ViewModel is composed on the client, so there is no server response
// header from which to derive its live-invalidation registrations.
private struct ViewModelMacroDiagnostic: DiagnosticMessage {
    let message: String
    let diagnosticID: MessageID
    let severity: DiagnosticSeverity

    static let liveClientHostedConflict = ViewModelMacroDiagnostic(
        message: "'.live' cannot be combined with '.clientHostedFactory': a client-hosted ViewModel is built on the client and has no server response to derive live registrations from",
        diagnosticID: MessageID(domain: "FOSMacros", id: "liveClientHostedConflict"),
        severity: .error
    )
}

// Example:
//
// @ViewModel
// struct MyViewModel/* : ViewModel <- No need to add, will be added automatically */ {
//   @LocalizableString public var myStr
//   @LocalizableInt public var myInt = 25
//
//   // This function is generated by the macro
//   public func propertyNames() -> [LocalizableId: String] { [
//      myStr.localizationId: "myStr",
//      myInt.localizationId: "myInt"
//   ] }
// }
//

private enum ViewModelOptions: String {
    /// Generate ``ClientHostedViewModelFactory`` support
    case clientHostedFactory

    /// Emit the ``LiveViewModel`` marker conformance
    case live
}

public struct ViewModelMacro: ExtensionMacro, MemberMacro {
    private static let knownLocalizedPropertyNames = [
        // _LocalizedProperty
        "LocalizedString",
        "LocalizedInt",
        "LocalizedDouble",
        "LocalizedDate",
        "LocalizedCompoundString",
        "LocalizedSubs",

        // _LocalizedArrayProperty
        "LocalizedStrings"
    ]

    // MARK: Extension Macro Protocol

    public static func expansion(
        of node: AttributeSyntax,
        attachedTo declaration: some DeclGroupSyntax,
        providingExtensionsOf type: some TypeSyntaxProtocol,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [ExtensionDeclSyntax] {
        guard node.attributeName.description.trimmingCharacters(in: .whitespaces) == "ViewModel" else {
            return []
        }

        // Ensure the declaration is a struct
        guard let structDecl = declaration.as(StructDeclSyntax.self) else {
            throw ViewModelMacroError.onlyStructs
        }

        let options = node.vmOptions

        // v1 constraint (spec §3.4): `.live` derives its registration set from the server response,
        // which a client-hosted ViewModel never has. Reject the combination up front.
        if options.contains(.live), options.contains(.clientHostedFactory) {
            context.diagnose(Diagnostic(
                node: node,
                message: ViewModelMacroDiagnostic.liveClientHostedConflict
            ))
            return []
        }

        var result = [ExtensionDeclSyntax]()

        // Skip extension generation if ViewModel is explicitly declared
        // Note: Indirect conformances (via other protocols) are not detected due to SwiftSyntax limitations
        if !structDecl.conformsTo("ViewModel") {
            // Create an extension with ViewModel conformance
            let extensionDecl = ExtensionDeclSyntax(
                extendedType: type,
                inheritanceClause: InheritanceClauseSyntax {
                    InheritedTypeSyntax(type: TypeSyntax(stringLiteral: "ViewModel"))
                },
                memberBlock: MemberBlockSyntax(members: [])
            )

            result.append(extensionDecl)
        }

        // Skip extension generation if ViewModel is explicitly declared
        // Note: Indirect conformances (via other protocols) are not detected due to SwiftSyntax limitations
        if !structDecl.conformsTo("RetrievablePropertyNames") {
            // Create an extension with ViewModel conformance
            let extensionDecl = ExtensionDeclSyntax(
                extendedType: type,
                inheritanceClause: InheritanceClauseSyntax {
                    InheritedTypeSyntax(type: TypeSyntax(stringLiteral: "RetrievablePropertyNames"))
                },
                memberBlock: MemberBlockSyntax(members: [])
            )

            result.append(extensionDecl)
        }

        if options.contains(.clientHostedFactory) {
            if !structDecl.conformsTo("ClientHostedViewModelFactory") {
                let requestableProtoDecl = structDecl.conformsTo("RequestableViewModel")
                    ? ""
                    : ", RequestableViewModel"

                let extensionDecl = try ExtensionDeclSyntax(
                    """
                    extension \(type): ClientHostedViewModelFactory\(raw: requestableProtoDecl) {
                    }
                    """
                )

                result.append(extensionDecl)
            }
        }

        // `.live` synthesizes the ``LiveViewModel`` marker and nothing else (spec §3.4). It refines
        // `RequestableViewModel`, so declaring `: LiveViewModel` carries that conformance — no
        // separate `RequestableViewModel` extension is needed here.
        if options.contains(.live), !structDecl.conformsTo("LiveViewModel") {
            let extensionDecl = try ExtensionDeclSyntax(
                """
                extension \(type): LiveViewModel {
                }
                """
            )

            result.append(extensionDecl)
        }

        return result
    }

    public static func expansion(
        of node: AttributeSyntax,
        providingMembersOf declaration: some DeclGroupSyntax,
        conformingTo protocols: [TypeSyntax],
        in context: some MacroExpansionContext
    ) throws -> [DeclSyntax] {
        guard node.attributeName.description.trimmingCharacters(in: .whitespaces) == "ViewModel" else {
            return []
        }

        // Ensure the declaration is a struct
        guard let structDecl = declaration.as(StructDeclSyntax.self) else {
            throw ViewModelMacroError.onlyStructs
        }

        let options = node.vmOptions

        // The conflict is diagnosed once in the extension role; here we only decline to emit members
        // so the invalid combination produces no half-formed expansion.
        if options.contains(.live), options.contains(.clientHostedFactory) {
            return []
        }

        let viewModelName = structDecl.name.text

        // Collect properties with _LocalizedProperty wrapper
        let properties = structDecl.memberBlock.members.compactMap { member -> (name: String, id: String)? in
            guard let varDecl = member.decl.as(VariableDeclSyntax.self),
                  let binding = varDecl.bindings.first,
                  let identifier = binding.pattern.as(IdentifierPatternSyntax.self)?.identifier.text
            else {
                return nil
            }

            // Check for LocalizableString or LocalizableInt attributes
            let hasLocalizedWrapper = varDecl.attributes.contains { attribute in
                guard let attr = attribute.as(AttributeSyntax.self) else { return false }
                let attrName = attr.attributeName.description.trimmingCharacters(in: .whitespaces)
                return Self.knownLocalizedPropertyNames.contains(attrName)
            }

            guard hasLocalizedWrapper else { return nil }

            return (name: identifier, id: "\(identifier).localizationId")
        }

        var newDecls: [DeclSyntax] = []

        if options.contains(.clientHostedFactory) {
            let parameters = structDecl.initParams

            // Generate AppState struct
            let appStateProperties = parameters.map { param in
                "public let \(param.name): \(param.type)"
            }.joined(separator: "\n")

            let appStateInitParameters = parameters.map { param in
                "\(param.name): \(param.type)"
            }.joined(separator: ", ")

            let appStateInitAssignments = parameters.map { param in
                "self.\(param.name) = \(param.name)"
            }.joined(separator: "\n")

            // Generate model function
            let modelInitArgs = parameters.map { param in
                "\(param.name): context.appState.\(param.name)"
            }.joined(separator: ", ")

            let typeAliasDecl = try TypeAliasDeclSyntax(
                "public typealias Request = ClientHostedRequest"
            )
            newDecls.append(DeclSyntax(typeAliasDecl))

            let appStateDecl = try StructDeclSyntax(
                """
                public struct AppState: Hashable, Sendable {
                    \(raw: appStateProperties)

                    public init(\(raw: appStateInitParameters)) {
                        \(raw: appStateInitAssignments)
                    }
                }
                """
            )
            newDecls.append(DeclSyntax(appStateDecl))

            let requestClass = try ClassDeclSyntax(
                """
                public final class ClientHostedRequest: ViewModelRequest, @unchecked Sendable {
                    public var responseBody: \(raw: viewModelName)?
                    public typealias ResponseError = EmptyError
                    public init(
                        query: EmptyQuery?,
                        sort: EmptySort? = nil,
                        fragment: EmptyFragment? = nil,
                        requestBody: EmptyBody? = nil,
                        responseBody: \(raw: viewModelName)?
                    ) {
                        self.responseBody = responseBody
                    }
                }
                """
            )
            newDecls.append(DeclSyntax(requestClass))

            // Generate synchronous helper - does the actual work
            let modelSyncDecl = try FunctionDeclSyntax(
                """
                public static func modelSync(
                    context: ClientHostedModelFactoryContext<Request, AppState>
                ) throws -> Self {
                    .init(\(raw: modelInitArgs))
                }
                """
            )
            newDecls.append(DeclSyntax(modelSyncDecl))

            // Generate async wrapper that satisfies ViewModelFactory protocol
            let modelDecl = try FunctionDeclSyntax(
                """
                public static func model(
                    context: ClientHostedModelFactoryContext<Request, AppState>
                ) async throws -> Self {
                    try modelSync(context: context)
                }
                """
            )
            newDecls.append(DeclSyntax(modelDecl))
        }

        // Synthesize the `Stubbable` witness `stub()` when the VM provides a
        // fully-defaulted parameterized `stub(...)` but no zero-arg `stub()`.
        // Swift does not let a defaulted parameter satisfy the no-arg requirement,
        // so we forward each parameter with its default made *explicit* — the call
        // then binds unambiguously to the parameterized overload rather than
        // recursing back into this witness.
        if let stubSource = structDecl.stubWitnessSource {
            let stubDecl = try FunctionDeclSyntax(
                """
                public static func stub() -> Self {
                    Self.stub(\(raw: stubSource.forwardingDefaultArguments))
                }
                """
            )
            newDecls.append(DeclSyntax(stubDecl))
        }

        // Generate the propertyNames function
        var pairs = properties.map { "_\($0.id): \"\($0.name)\"" }.joined(separator: ", ")
        if pairs.isEmpty {
            pairs = ":"
        }
        let propertyNamesDecl = try FunctionDeclSyntax(
            """
            public func propertyNames() -> [LocalizableId: String] {
                [\(raw: pairs)]
            }
            """
        )
        newDecls.append(DeclSyntax(propertyNamesDecl))

        return newDecls
    }
}

private extension AttributeSyntax {
    var vmOptions: Set<ViewModelOptions> {
        if let argumentList = arguments?.as(LabeledExprListSyntax.self),
           let optionsElement = argumentList.first(where: { $0.label?.text == "options" }),
           let arrayExpr = optionsElement.expression.as(ArrayExprSyntax.self) {
            Set(arrayExpr.elements.map(\.expression)
                .compactMap { $0.as(MemberAccessExprSyntax.self)?.declName }
                .map(\.baseName.text)
                .compactMap { ViewModelOptions(rawValue: $0) })
        } else {
            []
        }
    }
}

private extension StructDeclSyntax {
    func conformsTo(_ protocolName: String) -> Bool {
        inheritanceClause?.inheritedTypes.contains { inheritedType in
            if let identifierType = inheritedType.type.as(IdentifierTypeSyntax.self) {
                identifierType.name.text == protocolName
            } else {
                false
            }
        } ?? false
    }

    /// The parameterized `static func stub(...)` the synthesized `Stubbable`
    /// witness should forward to, or `nil` when the macro should not synthesize one.
    ///
    /// Returns `nil` when a zero-parameter `static func stub()` already satisfies
    /// the witness, or when no parameterized `stub(...)` has *all* parameters
    /// defaulted (the macro cannot invent argument values, so it stays out of the
    /// way and lets the normal `Stubbable` conformance error surface).
    var stubWitnessSource: FunctionDeclSyntax? {
        let stubFuncs = memberBlock.members
            .compactMap { $0.decl.as(FunctionDeclSyntax.self) }
            .filter { $0.name.text == "stub" && $0.isStatic }

        // A zero-arg stub() already witnesses Stubbable — never overload it.
        guard !stubFuncs.contains(where: \.signature.parameterClause.parameters.isEmpty)
        else { return nil }

        // Only a stub(...) with every parameter defaulted can be forwarded no-arg.
        return stubFuncs.first { fn in
            let params = fn.signature.parameterClause.parameters
            return !params.isEmpty && params.allSatisfy { $0.defaultValue != nil }
        }
    }

    var initParams: [(name: String, type: String)] {
        let initializers = memberBlock.members.compactMap {
            $0.decl.as(InitializerDeclSyntax.self)
        }
        guard let initializer = initializers.first else {
            return []
        }
        // Extract parameters from initializer
        return initializer.signature.parameterClause.parameters.compactMap { param -> (name: String, type: String)? in
            guard let typeAnnotation = TypeSyntax(param.type)?.description else {
                return nil
            }
            return (name: param.firstName.text, type: typeAnnotation)
        }
    }
}

private extension FunctionDeclSyntax {
    var isStatic: Bool {
        modifiers.contains { $0.name.tokenKind == .keyword(.static) }
    }

    /// A call-argument list that passes every parameter its own default value
    /// explicitly, e.g. `count: 8, name: "x"`. A parameter with an omitted
    /// external label (`_`) is forwarded positionally.
    var forwardingDefaultArguments: String {
        signature.parameterClause.parameters.compactMap { param -> String? in
            guard let defaultValue = param.defaultValue?.value.trimmed.description else {
                return nil
            }
            let label = param.firstName.text
            return label == "_" ? defaultValue : "\(label): \(defaultValue)"
        }.joined(separator: ", ")
    }
}
#endif
