name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tests:
    name: Test Swift v${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.7", "5.8"]
      fail-fast: false
    steps:
      - uses: swift-actions/setup-swift@v1
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v2

      - name: Run Tests
        run: swift test

  run_tests_windows:
    name: Test Swift v${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest]
        swift: ["5.7", "5.8"]
      fail-fast: false
    steps:
      - uses: compnerd/gha-setup-swift@main
        with:
          branch: swift-${{ matrix.swift }}-release
          tag: ${{ matrix.swift }}-release
      - uses: actions/checkout@v2

      - name: Run Tests
        run: swift test
      
  #####################################
  # swift 5.8 has removed generate-xcodeproj, so we'll need to find a different
  # way to do this.  I'm sure there will be an update soon.
  #####################################

  # analyze_code_coverage:
  #   runs-on: macos-12
  #   steps:
  #    - uses: actions/checkout@v2

  #    - name: Generate an xcodeproj
  #      run: swift package generate-xcodeproj

  #    - name: Run Tests w/ code coverage
  #      run: xcodebuild test -scheme CryptoScraper-Package -destination platform="macOS" -enableCodeCoverage YES

  #    - name: Upload coverage reports to Codecov
  #      uses: codecov/codecov-action@v3