name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tests:
    name: Test Swift v${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        swift: ["6.0.3"]
      fail-fast: false
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            swift build
          else
            swift test
          fi
        shell: bash
 
  # Ensure that compilation succeeds via xcodebuild
  run_xcodebuild_tests:
    name: Buiild ${{ matrix.ios_platform }} via Xcodebuild 'latest-stable'
    runs-on: macos-latest
    strategy:
      matrix:
        ios_platform: ["macos", "ios", "watchos", "tvos", "visionos"]

    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable

      - uses: actions/checkout@v2

      - name: Run ${{ matrix.ios_platform }} Build
        run: xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -skipMacroValidation -skipPackagePluginValidation -derivedDataPath "$PWD/.derivedData" build -scheme FOSUtilities-Package -destination "generic/platform=${{ matrix.ios_platform }}"
        if: matrix.ios_platform != 'macos'

      - name: Run ${{ matrix.ios_platform }} Build
        run: xcrun xcodebuild -IDEClonedSourcePackagesDirPathOverride="$PWD/.dependencies" -skipMacroValidation -skipPackagePluginValidation -derivedDataPath "$PWD/.derivedData" build -scheme FOSUtilities-Package -destination "platform=${{ matrix.ios_platform }},arch=arm64"
        if: matrix.ios_platform == 'macos'