name: CI

on:
  workflow_dispatch:
  pull_request:

jobs:
  run_tests:
    name: Test Swift v${{ matrix.swift }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        swift: ["6.0.3"]
      fail-fast: false
    steps:
      - uses: SwiftyLab/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift }}

      - uses: actions/checkout@v2

      - name: Run Tests
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            swift build
          else
            swift test
          fi
        shell: bash
 